menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/qilin55

favicon: /rose-qilin.jpg
logo: /rose-qilin.jpg

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2015
